import { Company, type CompanyFields } from "../types/company.js";

export const SEED_OWNER_EMAIL = "mcrysler@nimblegravity.com";

const EMPTY_OPTIONAL: Omit<CompanyFields, "id" | "project_name" | "account_name"> = {
  industry: null,
  annual_revenue: null,
  employee_head_count: null,
  year_founded: null,
  ebitda: null,
  ebitda_margin: null,
  days_since_last_activity: null,
  website: null,
  source_scrub_url: null,
  linked_in_company_id: null,
  zoom_info_company_id: null,
  growth_rate_12_months: null,
  growth_rate_9_months: null,
  growth_rate_6_months: null,
  investors: null,
  name: null,
  description: null,
  stage_name: null,
  type: null,
  lead_source: null,
  opportunity_owner: null,
  opportunity_owner_role: null,
  opportunity_owner_email: null,
  status: null,
};

const OWNER = {
  opportunity_owner: "Matt Crysler",
  opportunity_owner_role: "Managing Director",
  opportunity_owner_email: SEED_OWNER_EMAIL,
} as const;

export function seedCompany(
  fields: Pick<CompanyFields, "id" | "project_name" | "account_name"> &
    Partial<CompanyFields>,
): Company {
  return new Company({
    ...EMPTY_OPTIONAL,
    ...OWNER,
    ...fields,
  });
}

/** Rich in-memory opportunities for local development (DATA_STORE=memory). */
export const MEMORY_SEED_COMPANIES: Company[] = [
  seedCompany({
    id: "opp-001",
    project_name: "Northwind Expansion",
    account_name: "Northwind Traders",
    industry: "Manufacturing",
    annual_revenue: 45_000_000,
    employee_head_count: 320,
    year_founded: 1998,
    ebitda: 8_500_000,
    ebitda_margin: 0.189,
    days_since_last_activity: 4,
    website: "https://northwind.example.com",
    source_scrub_url: "https://sourcescrub.example.com/northwind-traders",
    linked_in_company_id: "northwind-traders",
    zoom_info_company_id: "ZI-10001",
    growth_rate_12_months: 0.12,
    growth_rate_9_months: 0.09,
    growth_rate_6_months: 0.06,
    investors: "Summit Partners; River Capital",
    name: "Northwind Expansion Opportunity",
    description:
      "Expansion initiative to modernize ERP and enter two new regional markets in the Midwest.",
    stage_name: "Qualification",
    type: "New Business",
    lead_source: "Partner Referral",
    status: "Open",
  }),
  seedCompany({
    id: "opp-002",
    project_name: "Contoso Platform",
    account_name: "Contoso Ltd",
    industry: "Technology",
    annual_revenue: 88_000_000,
    employee_head_count: 540,
    year_founded: 2004,
    ebitda: 19_500_000,
    ebitda_margin: 0.221,
    days_since_last_activity: 2,
    website: "https://contoso.example.com",
    source_scrub_url: "https://sourcescrub.example.com/contoso",
    linked_in_company_id: "contoso-ltd",
    zoom_info_company_id: "ZI-10002",
    growth_rate_12_months: 0.18,
    growth_rate_9_months: 0.14,
    growth_rate_6_months: 0.11,
    investors: "Horizon Growth; Blue Oak Ventures",
    name: "Contoso Cloud Platform",
    description:
      "Multi-year platform deal spanning analytics, identity, and customer data integration.",
    stage_name: "Proposal",
    type: "Existing Customer",
    lead_source: "Web",
    status: "In Review",
  }),
  seedCompany({
    id: "opp-003",
    project_name: "Fabrikam Health",
    account_name: "Fabrikam Inc",
    industry: "Healthcare",
    annual_revenue: 62_000_000,
    employee_head_count: 410,
    year_founded: 1992,
    ebitda: 11_200_000,
    ebitda_margin: 0.181,
    days_since_last_activity: 7,
    website: "https://fabrikam.example.com",
    source_scrub_url: "https://sourcescrub.example.com/fabrikam",
    linked_in_company_id: "fabrikam-health",
    zoom_info_company_id: "ZI-10003",
    growth_rate_12_months: 0.09,
    growth_rate_9_months: 0.07,
    growth_rate_6_months: 0.05,
    investors: "Meridian Health Partners",
    name: "Fabrikam Regional Network",
    description: "Clinical operations consolidation across six hospital affiliates.",
    stage_name: "Negotiation",
    type: "New Business",
    lead_source: "Conference",
    status: "Open",
  }),
  seedCompany({
    id: "opp-004",
    project_name: "Adventure Works Rollout",
    account_name: "Adventure Works",
    industry: "Retail",
    annual_revenue: 120_000_000,
    employee_head_count: 2400,
    year_founded: 1985,
    ebitda: 28_000_000,
    ebitda_margin: 0.233,
    days_since_last_activity: 1,
    website: "https://adventureworks.example.com",
    source_scrub_url: "https://sourcescrub.example.com/adventure-works",
    linked_in_company_id: "adventure-works",
    zoom_info_company_id: "ZI-10004",
    growth_rate_12_months: 0.06,
    growth_rate_9_months: 0.05,
    growth_rate_6_months: 0.04,
    investors: "Retail Growth Fund",
    name: "Adventure Works Omnichannel",
    description: "Completed rollout of inventory and loyalty systems to 180 stores.",
    stage_name: "Closed Won",
    type: "Existing Customer",
    lead_source: "Existing Customer",
    status: "Won",
  }),
  seedCompany({
    id: "opp-005",
    project_name: "Tailspin Pilot",
    account_name: "Tailspin Toys",
    industry: "Consumer Goods",
    annual_revenue: 18_500_000,
    employee_head_count: 95,
    year_founded: 2011,
    ebitda: 2_100_000,
    ebitda_margin: 0.114,
    days_since_last_activity: 21,
    website: "https://tailspintoys.example.com",
    source_scrub_url: "https://sourcescrub.example.com/tailspin",
    linked_in_company_id: "tailspin-toys",
    zoom_info_company_id: "ZI-10005",
    growth_rate_12_months: 0.22,
    growth_rate_9_months: 0.19,
    growth_rate_6_months: 0.15,
    investors: "Seed Stage Collective",
    name: "Tailspin D2C Pilot",
    description: "Pilot program for direct-to-consumer fulfillment and subscription bundles.",
    stage_name: "Discovery",
    type: "New Business",
    lead_source: "Cold Outreach",
    status: "Open",
  }),
  seedCompany({
    id: "opp-006",
    project_name: "Alpine Logistics Hub",
    account_name: "Alpine Transport",
    industry: "Transportation",
    annual_revenue: 210_000_000,
    employee_head_count: 1800,
    year_founded: 1978,
    ebitda: 31_500_000,
    ebitda_margin: 0.15,
    days_since_last_activity: 3,
    website: "https://alpine-transport.example.com",
    source_scrub_url: "https://sourcescrub.example.com/alpine-transport",
    linked_in_company_id: "alpine-transport",
    zoom_info_company_id: "ZI-10006",
    growth_rate_12_months: 0.08,
    growth_rate_9_months: 0.06,
    growth_rate_6_months: 0.04,
    investors: "Infrastructure Capital",
    name: "Alpine Midwest Hub",
    description: "Greenfield logistics hub serving automotive and industrial shippers.",
    stage_name: "Qualification",
    type: "New Business",
    lead_source: "Partner Referral",
    status: "Open",
  }),
  seedCompany({
    id: "opp-007",
    project_name: "Litware Analytics",
    account_name: "Litware Inc",
    industry: "Technology",
    annual_revenue: 34_000_000,
    employee_head_count: 210,
    year_founded: 2016,
    ebitda: 6_800_000,
    ebitda_margin: 0.2,
    days_since_last_activity: 5,
    website: "https://litware.example.com",
    source_scrub_url: "https://sourcescrub.example.com/litware",
    linked_in_company_id: "litware-inc",
    zoom_info_company_id: "ZI-10007",
    growth_rate_12_months: 0.31,
    growth_rate_9_months: 0.27,
    growth_rate_6_months: 0.24,
    investors: "Signal Peak; Northbridge Ventures",
    name: "Litware BI Suite",
    description: "Embedded analytics package for mid-market SaaS portfolios.",
    stage_name: "Proposal",
    type: "New Business",
    lead_source: "Web",
    status: "In Review",
  }),
  seedCompany({
    id: "opp-008",
    project_name: "Wide World Importers",
    account_name: "Wide World Importers",
    industry: "Wholesale",
    annual_revenue: 95_000_000,
    employee_head_count: 620,
    year_founded: 1990,
    ebitda: 14_250_000,
    ebitda_margin: 0.15,
    days_since_last_activity: 9,
    website: "https://wideworldimporters.example.com",
    source_scrub_url: "https://sourcescrub.example.com/wide-world",
    linked_in_company_id: "wide-world-importers",
    zoom_info_company_id: "ZI-10008",
    growth_rate_12_months: 0.05,
    growth_rate_9_months: 0.04,
    growth_rate_6_months: 0.03,
    investors: "Distribution Partners LP",
    name: "Wide World Sourcing",
    description: "Global sourcing desk expansion with vendor risk scoring.",
    stage_name: "Negotiation",
    type: "Existing Customer",
    lead_source: "Existing Customer",
    status: "Open",
  }),
  seedCompany({
    id: "opp-009",
    project_name: "Blue Yonder Marine",
    account_name: "Blue Yonder Holdings",
    industry: "Marine",
    annual_revenue: 52_000_000,
    employee_head_count: 280,
    year_founded: 2001,
    ebitda: 9_400_000,
    ebitda_margin: 0.181,
    days_since_last_activity: 14,
    website: "https://blueyonder.example.com",
    source_scrub_url: "https://sourcescrub.example.com/blue-yonder",
    linked_in_company_id: "blue-yonder-marine",
    zoom_info_company_id: "ZI-10009",
    growth_rate_12_months: 0.11,
    growth_rate_9_months: 0.1,
    growth_rate_6_months: 0.08,
    investors: "Harbor Equity",
    name: "Blue Yonder Fleet Services",
    description: "Aftermarket parts network and predictive maintenance for commercial fleets.",
    stage_name: "Discovery",
    type: "New Business",
    lead_source: "Conference",
    status: "Open",
  }),
  seedCompany({
    id: "opp-010",
    project_name: "Proseware Content Cloud",
    account_name: "Proseware Systems",
    industry: "Media",
    annual_revenue: 27_500_000,
    employee_head_count: 175,
    year_founded: 2008,
    ebitda: 4_950_000,
    ebitda_margin: 0.18,
    days_since_last_activity: 6,
    website: "https://proseware.example.com",
    source_scrub_url: "https://sourcescrub.example.com/proseware",
    linked_in_company_id: "proseware",
    zoom_info_company_id: "ZI-10010",
    growth_rate_12_months: 0.16,
    growth_rate_9_months: 0.13,
    growth_rate_6_months: 0.1,
    investors: "Storyline Media Fund",
    name: "Proseware Editorial Cloud",
    description: "Rights management and syndication workflow for publisher groups.",
    stage_name: "Qualification",
    type: "New Business",
    lead_source: "Web",
    status: "Open",
  }),
  seedCompany({
    id: "opp-011",
    project_name: "Graphic Design Institute",
    account_name: "Graphic Design Institute",
    industry: "Education",
    annual_revenue: 12_000_000,
    employee_head_count: 85,
    year_founded: 2014,
    ebitda: 1_800_000,
    ebitda_margin: 0.15,
    days_since_last_activity: 11,
    website: "https://gdi.example.com",
    source_scrub_url: "https://sourcescrub.example.com/gdi",
    linked_in_company_id: "graphic-design-institute",
    zoom_info_company_id: "ZI-10011",
    growth_rate_12_months: 0.14,
    growth_rate_9_months: 0.12,
    growth_rate_6_months: 0.09,
    investors: "EdGrowth Angels",
    name: "GDI Online Campus",
    description: "LMS migration and employer partnership portal for design programs.",
    stage_name: "Proposal",
    type: "New Business",
    lead_source: "Cold Outreach",
    status: "In Review",
  }),
  seedCompany({
    id: "opp-012",
    project_name: "Southridge Video",
    account_name: "Southridge Storage",
    industry: "Media",
    annual_revenue: 41_000_000,
    employee_head_count: 230,
    year_founded: 1999,
    ebitda: 7_800_000,
    ebitda_margin: 0.19,
    days_since_last_activity: 2,
    website: "https://southridge.example.com",
    source_scrub_url: "https://sourcescrub.example.com/southridge",
    linked_in_company_id: "southridge-storage",
    zoom_info_company_id: "ZI-10012",
    growth_rate_12_months: 0.07,
    growth_rate_9_months: 0.06,
    growth_rate_6_months: 0.05,
    investors: "Catalyst Media Partners",
    name: "Southridge Archive Platform",
    description: "Cold storage digitization and streaming rights catalog modernization.",
    stage_name: "Closed Won",
    type: "Existing Customer",
    lead_source: "Partner Referral",
    status: "Won",
  }),
  seedCompany({
    id: "opp-013",
    project_name: "City Power & Light",
    account_name: "City Power & Light",
    industry: "Utilities",
    annual_revenue: 340_000_000,
    employee_head_count: 3200,
    year_founded: 1962,
    ebitda: 48_000_000,
    ebitda_margin: 0.141,
    days_since_last_activity: 8,
    website: "https://citypower.example.com",
    source_scrub_url: "https://sourcescrub.example.com/city-power",
    linked_in_company_id: "city-power-light",
    zoom_info_company_id: "ZI-10013",
    growth_rate_12_months: 0.03,
    growth_rate_9_months: 0.025,
    growth_rate_6_months: 0.02,
    investors: "Municipal Infrastructure Trust",
    name: "City Power Grid Analytics",
    description: "Grid reliability analytics and outage prediction for metro service territory.",
    stage_name: "Negotiation",
    type: "New Business",
    lead_source: "Conference",
    status: "Open",
  }),
  seedCompany({
    id: "opp-014",
    project_name: "Humongous Insurance",
    account_name: "Humongous Insurance",
    industry: "Finance",
    annual_revenue: 275_000_000,
    employee_head_count: 2100,
    year_founded: 1972,
    ebitda: 42_000_000,
    ebitda_margin: 0.153,
    days_since_last_activity: 12,
    website: "https://humongous.example.com",
    source_scrub_url: "https://sourcescrub.example.com/humongous",
    linked_in_company_id: "humongous-insurance",
    zoom_info_company_id: "ZI-10014",
    growth_rate_12_months: 0.04,
    growth_rate_9_months: 0.035,
    growth_rate_6_months: 0.03,
    investors: "Stable Yield Partners",
    name: "Humongous Policy Admin",
    description: "Policy administration rewrite with claims integration and agent portal.",
    stage_name: "Qualification",
    type: "Existing Customer",
    lead_source: "Existing Customer",
    status: "Open",
  }),
  seedCompany({
    id: "opp-015",
    project_name: "Lucerne Publishing",
    account_name: "Lucerne Publishing",
    industry: "Media",
    annual_revenue: 22_000_000,
    employee_head_count: 140,
    year_founded: 2006,
    ebitda: 3_300_000,
    ebitda_margin: 0.15,
    days_since_last_activity: 18,
    website: "https://lucerne.example.com",
    source_scrub_url: "https://sourcescrub.example.com/lucerne",
    linked_in_company_id: "lucerne-publishing",
    zoom_info_company_id: "ZI-10015",
    growth_rate_12_months: 0.1,
    growth_rate_9_months: 0.08,
    growth_rate_6_months: 0.06,
    investors: "Chapter One Capital",
    name: "Lucerne Subscription Stack",
    description: "Paywall, fulfillment, and subscriber analytics for specialty publishers.",
    stage_name: "Discovery",
    type: "New Business",
    lead_source: "Web",
    status: "Open",
  }),
  seedCompany({
    id: "opp-999",
    project_name: "Other Owner Co",
    account_name: "Other Corp",
    industry: "Finance",
    annual_revenue: 15_000_000,
    employee_head_count: 60,
    year_founded: 2018,
    ebitda: 2_000_000,
    ebitda_margin: 0.133,
    days_since_last_activity: 30,
    website: "https://other.example.com",
    source_scrub_url: "https://sourcescrub.example.com/other-corp",
    linked_in_company_id: "other-corp",
    zoom_info_company_id: "ZI-99999",
    growth_rate_12_months: 0.05,
    growth_rate_9_months: 0.04,
    growth_rate_6_months: 0.03,
    investors: "Outside Fund",
    name: "Other Owner Opportunity",
    description: "Owned by another user for access-control testing.",
    stage_name: "Qualification",
    type: "New Business",
    lead_source: "Web",
    status: "Open",
    opportunity_owner: "Alex Other",
    opportunity_owner_role: "Associate",
    opportunity_owner_email: "other.user@example.com",
  }),
];

/** Opportunities returned for the default seed owner in memory mode. */
export const MEMORY_SEED_OWNER_COUNT = MEMORY_SEED_COMPANIES.filter(
  (c) => c.opportunity_owner_email === SEED_OWNER_EMAIL,
).length;
